### ISSUE TITLE
link from readme to an existing deployment (demo)?

### ISSUE THREAD

**Issue by nruth** [ur0/statusify#15]
I see there's a deploy-to-heroku button, but a link to an existing deployment would be nice for people to quickly take a look around what this does.

**Comment by gerard-leijdekkers** [comment]
+1

**Comment by ur0** [comment]
Oh sure. I've got a demo up at https://statusify-dev.herokuapp.com/ Feel free to file a PR.

**Comment by donv** [comment]
Link added in PR #17 .
