### ISSUE TITLE
Error happen when try deploying to Heroku by heroku button

### ISSUE THREAD

**Issue by ecleel** [ur0/statusify#18]
Hi,

I tried to deploy it with Heroku button but it seems something wrong in app.json file
![screen shot 2015-10-09 at 2 10 01 pm](https://cloud.githubusercontent.com/assets/25447/10392432/b882620a-6e8f-11e5-8a75-e198284af084.png)

Also it also helpful if you have a screen shot for the homepage of the project.

Thanks.

**Comment by ur0** [comment]
Hi,

Thanks for reporting. This is happening since the button tries to deploy the `master` branch, which doesn't have any code. I'll make it deploy from `development` till we merge to master.
